
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Scanner;

import javax.swing.JOptionPane;

public class ManagerMenu extends javax.swing.JFrame {
	static double totalProfit;

	/**
	 * Creates new form ManagerMenu
	 */
	public ManagerMenu() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		buttonGroup1 = new javax.swing.ButtonGroup();
		jPanel1 = new javax.swing.JPanel();
		jPanel2 = new javax.swing.JPanel();
		jLabel3 = new javax.swing.JLabel();
		jRadioButton1 = new javax.swing.JRadioButton();
		jRadioButton2 = new javax.swing.JRadioButton();
		jRadioButton3 = new javax.swing.JRadioButton();
		jLabel4 = new javax.swing.JLabel();
		jRadioButton4 = new javax.swing.JRadioButton();
		jRadioButton5 = new javax.swing.JRadioButton();
		jRadioButton6 = new javax.swing.JRadioButton();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jPanel1.setBackground(new java.awt.Color(0, 102, 102));

		jPanel2.setBackground(new java.awt.Color(255, 255, 255));

		jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
		buttonGroup1.add(jRadioButton1);
		jRadioButton1.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
		jRadioButton1.setForeground(new java.awt.Color(0, 102, 102));
		jRadioButton1.setText("Συνολικά Κέρδη Επιχείρησης");
		jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton1ActionPerformed(evt);
			}
		});

		jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
		buttonGroup1.add(jRadioButton2);
		jRadioButton2.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
		jRadioButton2.setForeground(new java.awt.Color(0, 102, 102));
		jRadioButton2.setText("Αλλαγή ποσού Προϋπολογισμού");
		jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton2ActionPerformed(evt);
			}
		});

		jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
		buttonGroup1.add(jRadioButton3);
		jRadioButton3.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
		jRadioButton3.setForeground(new java.awt.Color(0, 102, 102));
		jRadioButton3.setText("Απόδοση Πωλητών");
		jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton3ActionPerformed(evt);
			}
		});

		jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
		jLabel4.setForeground(new java.awt.Color(0, 102, 102));
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setText("Μενού Μάνατζερ");
		jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 102), 3));

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGroup(jPanel2Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(162, 162, 162).addComponent(jLabel3))
						.addGroup(jPanel2Layout.createSequentialGroup().addGap(136, 136, 136)
								.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jRadioButton2).addComponent(jRadioButton1)
										.addComponent(jRadioButton3))))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup().addGap(0, 79, Short.MAX_VALUE).addComponent(jLabel4,
								javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(69, 69, 69)));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(23, 23, 23).addComponent(jLabel4)
						.addGap(66, 66, 66).addComponent(jRadioButton1).addGap(83, 83, 83).addComponent(jRadioButton2)
						.addGap(92, 92, 92).addComponent(jRadioButton3).addGap(246, 246, 246).addComponent(jLabel3)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jRadioButton4.setBackground(new java.awt.Color(0, 102, 102));
		buttonGroup1.add(jRadioButton4);
		jRadioButton4.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
		jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
		jRadioButton4.setText("Μισθοί και Μπόνους πωλητών");
		jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton4ActionPerformed(evt);
			}
		});

		jRadioButton5.setBackground(new java.awt.Color(0, 102, 102));
		buttonGroup1.add(jRadioButton5);
		jRadioButton5.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
		jRadioButton5.setForeground(new java.awt.Color(255, 255, 255));
		jRadioButton5.setText("Τρεις καλύτεροι σε απόδοση πωλητές");
		jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton5ActionPerformed(evt);
			}
		});

		jRadioButton6.setBackground(new java.awt.Color(0, 102, 102));
		buttonGroup1.add(jRadioButton6);
		jRadioButton6.setFont(new java.awt.Font("Times New Roman", 0, 21)); // NOI18N
		jRadioButton6.setForeground(new java.awt.Color(255, 255, 255));
		jRadioButton6.setText("Εγγραφή νέου πωλητή");
		jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton6ActionPerformed(evt);
			}
		});

		jButton1.setForeground(new java.awt.Color(0, 102, 102));
		jButton1.setText("Αποσύνδεση");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE,
								javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
						.addGroup(
								jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel1Layout.createSequentialGroup().addGroup(jPanel1Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jRadioButton5).addComponent(jRadioButton4)
														.addComponent(jRadioButton6)).addGap(111, 111, 111))
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
												jPanel1Layout.createSequentialGroup()
														.addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
																116, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGap(37, 37, 37)))));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
						Short.MAX_VALUE)
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(132, 132, 132).addComponent(jRadioButton4)
						.addGap(80, 80, 80).addComponent(jRadioButton5).addGap(92, 92, 92).addComponent(jRadioButton6)
						.addGap(20, 20, 20).addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 500,
				Short.MAX_VALUE));

		pack();
	}// </editor-fold>

	private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		String url = "jdbc:sqlserver://195.251.249.161:1433;" + "databaseName=DB35;user=G535;password=48tr93905;";
		Connection dbcon;
		Statement stmt1; /* DataBase returns all Salesmen */
		ResultSet rs1;

		try {

			dbcon = DriverManager.getConnection(url);
			stmt1 = dbcon.createStatement();
			rs1 = stmt1.executeQuery("Select sum(profit) as TP  From Salesman");
			if (rs1.next()) {
				totalProfit = rs1.getDouble("TP");

				ManagerOption1 mn1 = new ManagerOption1();
				mn1.jTextField2.setText(String.valueOf(totalProfit) + " €");
				mn1.setVisible(true);

				dbcon.close();
				stmt1.close();
			}
		} catch (SQLException e) {
			System.out.print("SQLException: ");
			System.out.println(e.getMessage());
		}
	}

	private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		NewBudget nb = new NewBudget();
		nb.jLabel4.setText(String.valueOf(Manager.getBudget()));
		nb.setVisible(true);
	}

	private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		Manager.Print_All_Efficiencies();
	}

	private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		Manager.Print_All_Salaries();
	}

	private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		Manager.Top3_Salesmen();
	}

	private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		RegisterSalesman rs = new RegisterSalesman();
		rs.setVisible(true);
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		Welcome wl = new Welcome();
		setVisible(false);
		wl.setVisible(true);
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ManagerMenu.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ManagerMenu().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.ButtonGroup buttonGroup1;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JRadioButton jRadioButton1;
	private javax.swing.JRadioButton jRadioButton2;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JRadioButton jRadioButton4;
	private javax.swing.JRadioButton jRadioButton5;
	private javax.swing.JRadioButton jRadioButton6;
	// End of variables declaration
}